const ACTION_COLLAPSE = 'COLLAPSE_NODE';
const ACTION_LOCK = 'ACTION_LOCK';
const ACTION_ADD = 'ACTION_ADD';
const ACTION_RESIZE = 'ACTION_RESIZE';
const ACTION_LINK = 'ACTION_LINK';

const COLLAPSED_HEIGHT = 40;
const DEFAULT_NODE_INDENT = 400;
const FOOTER_WIDTH = 105;
const LINK_ICON_SIZE = 32;
const TYPE_ROOT = 1;

const SALT = 'tmp-node';

export {
  ACTION_COLLAPSE,
  ACTION_LOCK,
  ACTION_ADD,
  ACTION_RESIZE,
  ACTION_LINK,
  COLLAPSED_HEIGHT,
  DEFAULT_NODE_INDENT,
  FOOTER_WIDTH,
  LINK_ICON_SIZE,
  SALT,
  TYPE_ROOT,
};
