const ACTION_COLLAPSE = 'COLLAPSE_NODE';
const ACTION_LOCK = 'ACTION_LOCK';
const ACTION_ADD = 'ACTION_ADD';
const ACTION_RESIZE = 'ACTION_RESIZE';
const ACTION_LINK = 'ACTION_LINK';

const DEFAULT_WIDTH = 300;
const DEFAULT_HEIGHT = 160;
const COLLAPSED_HEIGHT = 40;
const DEFAULT_NODE_INDENT = 400;

export {
  ACTION_COLLAPSE,
  ACTION_LOCK,
  ACTION_ADD,
  ACTION_RESIZE,
  ACTION_LINK,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  COLLAPSED_HEIGHT,
  DEFAULT_NODE_INDENT,
};
