const COLLAPSE_NODE = 'COLLAPSE_NODE';
const LOCK_NODE = 'LOCK_NODE';
const ADD_NODE = 'ADD_NODE';
const RESIZE_NODE = 'RESIZE_NODE';
const LINK_NODE = 'LINK_NODE';

const DEFAULT_WIDTH = 300;
const DEFAULT_HEIGHT = 160;
const COLLAPSED_HEIGHT = 40;
const DEFAULT_NODE_INDENT = 400;

export {
  COLLAPSE_NODE,
  LOCK_NODE,
  ADD_NODE,
  RESIZE_NODE,
  LINK_NODE,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  COLLAPSED_HEIGHT,
  DEFAULT_NODE_INDENT,
};
