import randomColor from 'randomcolor';
import { DEFAULT_WIDTH, DEFAULT_HEIGHT } from '../app/Constructor/Graph/Node/config';

const ids = [...Array(4)].map((_, i) => Date.now() + i);
const mapId = Number(ids[0].toString().slice(0, 6));

const sample = {
  edges: [
    {
      isSelected: false,
      data: {
        id: 1,
        label: `Arrow-${1}`,
        source: ids[0],
        target: ids[1],
        color: '#D3DAE1',
        variant: 'Standard',
        thickness: 3,
        isHidden: false,
      },
    },
    {
      isSelected: false,
      data: {
        id: 2,
        label: `Arrow-${2}`,
        source: ids[0],
        target: ids[2],
        color: '#D3DAE1',
        variant: 'Standard',
        thickness: 3,
        isHidden: false,
      },
    },
    {
      isSelected: false,
      data: {
        id: 3,
        label: `Arrow-${3}`,
        source: ids[0],
        target: ids[3],
        color: '#D3DAE1',
        variant: 'Standard',
        thickness: 3,
        isHidden: false,
      },
    },
    {
      isSelected: false,
      data: {
        id: 4,
        label: `Arrow-${4}`,
        source: ids[3],
        target: ids[0],
        color: 'red',
        variant: 'Dashed',
        thickness: 5,
        isHidden: true,
      },
    },
  ],
  nodes: [
    {
      isSelected: false,
      data: {
        id: ids[0],
        type: 1,
        map_id: mapId,
        title: 'Root Node',
        x: 258.3976135253906,
        y: 331.9783248901367,
        width: DEFAULT_WIDTH,
        height: DEFAULT_HEIGHT,
        color: randomColor(),
        text: 'Course-level scope can be reused across any of the maps within the Course.',
        links: [],
        destination_id: mapId,
        style_id: mapId,
        type_id: mapId,
        isCollapsed: false,
        isLocked: false,
      },
    },
    {
      isSelected: false,
      data: {
        id: ids[1],
        type: 2,
        map_id: mapId,
        title: 'Some node',
        x: 593.9393920898438,
        y: 260.6060791015625,
        width: DEFAULT_WIDTH,
        height: DEFAULT_HEIGHT,
        color: randomColor(),
        text: 'Further up the tree of objects, an Administrator can edit Server-level and lower level objects. It would be rude to edit another author’s map-level objects without their permission, but the scope permissions would allow it. In such an event, it would be more proper to take a lower level object and save a copy to a higher scope level, and refine it for more broadly scoped use.',
        links: [],
        destination_id: mapId,
        style_id: mapId,
        type_id: mapId,
        isCollapsed: false,
        isLocked: false,
      },
    },
    {
      isSelected: false,
      data: {
        id: ids[2],
        type: 2,
        map_id: mapId,
        title: 'Some node',
        x: 237.5757598876953,
        y: 61.81818389892578,
        width: DEFAULT_WIDTH,
        height: DEFAULT_HEIGHT,
        color: randomColor(),
        text: 'So, who can access and edit these objects? A map author can create, edit and use a map-level object in their map, much as before. They can also use/insert an object which has broader scope (Course, Server, Global) into their map but they cannot edit it. They can make a copy of a higher level (broader scope) object, edit or customize it, and save that as a map-level object and then insert that into their map.',
        links: [],
        destination_id: mapId,
        style_id: mapId,
        type_id: mapId,
        isCollapsed: false,
        isLocked: false,
      },
    },
    {
      isSelected: false,
      data: {
        id: ids[3],
        type: 2,
        map_id: mapId,
        title: 'Some node',
        x: 0,
        y: 300,
        width: DEFAULT_WIDTH,
        height: DEFAULT_HEIGHT,
        color: randomColor(),
        text: 'The Editors for Scoped Objects will be fairly simple, separate pages, with a different editor for each Object type.',
        links: [],
        destination_id: mapId,
        style_id: mapId,
        type_id: mapId,
        isCollapsed: false,
        isLocked: false,
      },
    },
  ],
};

export default sample;
